### ISSUE TITLE
Redis connection error event handler is set ONLY after connection is established

### ISSUE THREAD

**Issue by YimingIsCOLD** [taskforcesh/bullmq#666]
Bull Version: 1.40.1

```ts
const queue = new Queue('test', {
    connection: {
        host: 'localhost',
        port: 6379,
    },
});

queue.on('error', () => console.log('Something went wrong!'));
```

An unhandled error event is logged by `IORedis` when creating a new queue with no redis server available.

```
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16)
```

If there is a redis server available during the queue creation and somehow lost connection to the redis server, the queue will emit an error with `Something went wrong!`.

After some investigation, I found out that [the error event hook is set after a `initializing` has been resolved](https://github.com/taskforcesh/bullmq/blob/master/src/classes/redis-connection.ts#L45). However, in the case where there is no redis server available during queue creation, it will be stuck in [`waitUntilReady` promise](https://github.com/taskforcesh/bullmq/blob/master/src/classes/redis-connection.ts#L66-L79) and thus not setting the error event hook.

I will suggest to place the hook at [here](https://github.com/taskforcesh/bullmq/blob/master/src/classes/redis-connection.ts#L91) instead of after the `initializing` has been resolved. What you do think?

**Comment by manast** [comment]
It sounds like a reasonable change.

**Comment by YimingIsCOLD** [comment]
Alright! I will create a PR to address this.

**Comment by YimingIsCOLD** [comment]
@manast How do I run the test locally? I got a fresh copy of the repo, did `yarn` and spin up a redis server with docker. When I tried to run the test with `yarn test`, it always failed with the following logs. I tried digging around but can't seems to find the root cause.

```
  connection
Error: ECONNRESET
    at Context.<anonymous> (/Users/yiming/workspace/bullmq/src/test/test_connection.ts:56:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ✓ should recover from a connection loss (39ms)
Error: ECONNRESET
    at Worker.<anonymous> (/Users/yiming/workspace/bullmq/src/test/test_connection.ts:105:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ✓ should handle jobs added before and after a redis disconnect
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:1234
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16)
    ✓ should fail if redis connection fails
    1) should fail if redis connection fails


  42 passing (4s)
  1 failing

  1) connection
       should fail if redis connection fails:
     Uncaught Error: Connection is closed.
      at Redis.endHandler (src/classes/redis-connection.ts:74:16)
      at Object.onceWrapper (node:events:514:26)
      at Redis.emit (node:events:394:28)
      at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by manast** [comment]
That is quite strange considering there are 231 tests in total...

**Comment by roggervalf** [comment]
@YimingIsCOLD could you please try the last version, a fix was merged

**Comment by lukepolo** [comment]
i just tired this , and it works kinda.....

```
 const connection = this.redisManager.getConnection(this.config.redisConnection);
    const bullQueueOptions: BullQueueOptions = {
      prefix: this.config.prefix,
      connection
    };

    this.queue = new BullMQ(this.queueName, bullQueueOptions || {}).on('error', (error) => {
      logger.error("queue error", error.message)
    })
  ```


```
 BullMQQueue <error> queue error Connection is closed. +0ms
(node:68495) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at Redis.errorHandler (/Users/luke/Code/work/qx-microservice-framework/qx-microservice-template/node_modules/bullmq/dist/classes/redis-connection.js:60:24)
    at Object.onceWrapper (events.js:421:26)
    at Redis.emit (events.js:326:22)
    at Redis.silentEmit (/Users/luke/Code/work/qx-microservice-framework/qx-microservice-template/node_modules/ioredis/built/redis/index.js:544:26)
    at Socket.<anonymous> (/Users/luke/Code/work/qx-microservice-framework/qx-microservice-template/node_modules/ioredis/built/redis/event_handler.js:190:14)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:326:22)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:68495) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:68495) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:68495) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at Redis.errorHandler (/Users/luke/Code/work/qx-microservice-framework/qx-microservice-template/node_modules/bullmq/dist/classes/redis-connection.js:60:24)
    at Object.onceWrapper (events.js:421:26)
    at Redis.emit (events.js:326:22)
    at Redis.silentEmit (/Users/luke/Code/work/qx-microservice-framework/qx-microservice-template/node_modules/ioredis/built/redis/index.js:544:26)
    at Socket.<anonymous> (/Users/luke/Code/work/qx-microservice-framework/qx-microservice-template/node_modules/ioredis/built/redis/event_handler.js:190:14)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:326:22)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:68495) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

The `Connection is closed` is fine but still seems to still have a unhandled rejection.

not a huge deal~

**Comment by roggervalf** [comment]
@lukepolo, yes you are right, that unhandled promise rejection has some time in the base code, but the fix was preventing the unhandled error event as @YimingIsCOLD mentioned. I'll need to make more investigation about the unhandled rejection.
