### ISSUE TITLE
Intermittent "Lua redis() command arguments must be strings or integers"

### ISSUE THREAD

**Issue by tmcgannon** [taskforcesh/bullmq#72]
This intermittent error is happening when moveToFinished Lua script is being called.  

When capturing the failed event [i.e. worker.on('failed', (job, error) => {...})] the following data is produced:

job:

``` json
{
    "id": "8",
    "name": "eml",
    "data": "{\"templateId\":\"server_shutdown\",\"subject\":\"[Meeting-Test] Server Report - Shutdown\",\"data\":{\"serverInfo\":{\"env\":\"MOCK_ENV\",\"version\":\"MOCK_VERSION\",\"hostName\":\"MOCK_HOST_NAME\"}},\"options\":{\"isDiagnosticEmail\":true,\"sendAsText\":true,\"skipToAccountBounceVerification\":true},\"toAccounts\":[{\"email\":\"foo@bar.com\"}]}",
    "opts": "{\"attempts\":0,\"delay\":0,\"removeOnComplete\":100}",
    "progress": 0,
    "attemptsMade": 1,
    "processedOn": 1574214599662,
    "timestamp": 1574214599674,
    "failedReason": "\"ERR Error running script (call to f_ae2c40fe4d28cbdf1e2fe57d1682bc203603a506): @user_script:107: @user_script: 107: Lua redis() command arguments must be strings or integers \"",
    "stacktrace": "[\"ReplyError: ERR Error running script (call to f_ae2c40fe4d28cbdf1e2fe57d1682bc203603a506): @user_script:107: @user_script: 107: Lua redis() command arguments must be strings or integers \\n    at parseError (~/server/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:179:12)\\n    at parseType (~/server/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:302:14)\"]",
    "returnvalue": "0"
}
```

error: 

``` json
{
    "command": {
        "name": "evalsha",
        "args": [
            "ae2c40fe4d28cbdf1e2fe57d1682bc203603a506",
            "7",
            "m2:emlq:active",
            "m2:emlq:completed",
            "m2:emlq:8",
            "m2:emlq:wait",
            "m2:emlq:priority",
            "m2:emlq:events",
            "m2:emlq:meta",
            "8",
            "1574214599677",
            "returnvalue",
            "null",
            "completed",
            "101",
            "{\"jobId\":\"8\"}",
            "0",
            "m2:emlq:",
            "0572fc7e-3069-4155-97b7-aafd738128ac",
            "30000"
        ]
    }
}
```

Notice that all of the args are strings.

Even when I insert my own logging code in scripts.ts, the args are as follows:

```
moveToFinished ARGS: [
  'm2:emlq:active',
  'm2:emlq:completed',
  'm2:emlq:8',
  'm2:emlq:wait',
  'm2:emlq:priority',
  'm2:emlq:events',
  'm2:emlq:meta',
  '8',
  1574214599677,
  'returnvalue',
  'null',
  'completed',
  '101',
  '{"jobId":"8"}',
  0,
  'm2:emlq:',
  '0572fc7e-3069-4155-97b7-aafd738128ac',
  30000
]
```

You can see that they are all integers and strings.

The unit test I am performing does 100 identical jobs in a row but only some produce this error.  Any thoughts on how I should track this down?

**Comment by stansv** [comment]
There're XTRIM on line 107 that fails,
```
106    local maxEvents = rcall("HGET", KEYS[7], "opts.maxLenEvents")
107    rcall("XTRIM", KEYS[6], "MAXLEN", "~", maxEvents)
```

So I can conclude meta key (`m2:emlq:meta` in your case) is missing or does not contain opts.maxLenEvents field when this happens.

@manast how do you think can we just use default value of 10000 here in script?

**Comment by manast** [comment]
not sure, what about not doing the trim if maxEvents is not defined? In any case, how can this happen?

**Comment by tmcgannon** [comment]
When I get the 'failed' event and I look at redis (KEYS <prefix>*), the only relevant keys are:

```
27.0.0.1:6379> keys m2*
1) "m2:emlq:completed"
2) "m2:emlq:1"
3) "m2:emlq:events"
4) "m2:emlq:id"
```

**Comment by stansv** [comment]
@manast I've also noticed this error some time ago. That was pretty convenient in Bull3 to have ability to manually remove queue entirely (or even flush DB) for test purposes — in case if there're no running jobs it had absolutely no side effects. But in BullMQ you have to re-initialize Queue object to write meta entry first.

**Comment by tmcgannon** [comment]
> @manast I've also noticed this error some time ago. That was pretty convenient in Bull3 to have ability to manually remove queue entirely (or even flush DB) for test purposes — in case if there're no running jobs it had absolutely no side effects. But in BullMQ you have to re-initialize Queue object to write meta entry first.

I'm trying to understand the above.  Can I use FLUSHALL to clear the redis database to get to a pristine state (e.g. before each of my unit tests)?

**Comment by stansv** [comment]
@tmcgannon this is now fixed with my PR, but for previous version you should call `new Queue()` each time after `FLUSHALL` in order to create that meta entry with `opts.maxLenEvents` field.

**Comment by yogendrajs** [comment]
still facing this error with the following dependencies version and the Redis server version `Redis 7.0.10 (00000000/0) 64 bit`- 
```
"dependencies": {
    "bullmq": "1.87.1",
    "ioredis": "4.28.5"
  }
```

**Comment by manast** [comment]
@yogendrajs you are on a very old version of BullMQ, why not upgrade to latest?

**Comment by aguidrevitch** [comment]
> For anyone who ends up here in the future, we encountered this error when some modules had been upgraded to `bullmq` but others had not. Upgrading all modules to `bullmq` seemed to fix the issue.

For me it seems there was a conflict with bull npm, used by another dependency. Once I got rid of bull npm, everything started to work

**Comment by laneme** [comment]
Passing `undefined` value for `name` indeed causes the error.

I think this will help someone, your node server needs to pick up values from generated code.
In my case updated enums values from prisma client wasnt being picked up by hmr.

**Comment by manast** [comment]
@laneme yeah, this kind of sucks because basically the alternative here would be to, using defensive programming, check all the input variables for all of BullMQ apis, which seems not right. I expect users to use Typescript. If you using env variables to define inputs for any apis that you may call in your code you should declare those variables as ```string | undefined``` as they could be very well undefined, so as I see it is a bug in user code, which in this case affects BullMQ and but it could affect anything else. So basically make sure you use proper typing and you should avoid this issues all together.

**Comment by laneme** [comment]
> it could affect anything else
@manast absolutely. And i agree with your point of views.

But you see the error wasnt immediately obvious in my case.
I had full editor typing from the generated variables, except my hmr from running dev server din't pick up the changed values. Leading to me have a false sense security that something must be broken inside bullmq

This kind of problem isnt uncommon in the wild.

Though honestly i prefer bullmq as is, because this is still technically user error. idk

**Comment by manast** [comment]
But if the env variable had the right declaration, then the compiler would have complained if you tried to pass it as an argument since the ```add``` method requires a ```string``` but an env variable must be ```string | undefined```, I appreciate that this is easy to miss, but we had issues in the past with other arguments such as Redis configuration also taken from env variables with invalid values and so on... it is sad but not really BullMQs responsibility to take care of in my opinion.

**Comment by manast** [comment]
I can add a text in the troubleshooting section though, so that at least it is documented and as a thing to check if things do not work properly.

**Comment by manast** [comment]
Here it is: https://docs.bullmq.io/guide/troubleshooting#invalid-or-undefined-environment-variables

**Comment by sahil28032005** [comment]
this is my etraction function:const validateParams = (session) => {
    const errors = [];

    if (!session.name || session.name.length < 2) errors.push("Project name must be at least 2 characters.");
    if (!session.description || session.description.length < 5) errors.push("Project description must be at least 5 characters.");
    if (!session.ownerId || isNaN(parseInt(session.ownerId))) errors.push("Owner ID must be a valid number.");
    if (!session.gitUrl || !/^https?:\/\/github\.com\/[\w-]+\/[\w-]+$/i.test(session.gitUrl)) {
        errors.push("Git URL must be a valid GitHub repository.");
    }

    return errors;
};

const chatbotController = async (req, res) => {
    try {
        const { message, userId } = req.body;
        if (!userId) return res.status(400).json({ message: "User ID is required." });

        // Initialize session if not exists
        if (!userSessions[userId]) {
            userSessions[userId] = {
                name: null,
                gitUrl: null,
                description: null,
                ownerId: null,
                askedParams: new Set(), // Track which params we've asked for
            };
        }
        let session = userSessions[userId];

        // Extract parameters from user message
        const userParams = extractParams(message);

        console.log("extracted params: ", userParams);

        // Update session with new valid parameters
        Object.entries(userParams).forEach(([key, value]) => {
            if (value) {
                session[key] = value;
                session.askedParams.delete(key); // Mark as collected
            }
        });

        // Identify missing parameters
        let missingParams = [];
        if (!session.name) missingParams.push("name");
        if (!session.gitUrl) missingParams.push("gitUrl");
        if (!session.description) missingParams.push("description");
        if (!session.ownerId) missingParams.push("ownerId");

        // If parameters are missing, ask for the next one
        if (missingParams.length > 0) {
            const nextParam = missingParams.find(param => !session.askedParams.has(param));

            if (nextParam) {
                session.askedParams.add(nextParam);
                let prompt = getPrompt(nextParam);

                // Show progress update
                const collectedCount = 4 - missingParams.length;
                if (collectedCount > 0) {
                    prompt = `Got ${collectedCount}/4 details! ${prompt}`;
                }

                return res.json({ reply: prompt });
            }
        }

        // ✅ All parameters collected, proceed with validation
        const validationErrors = validateParams(session);
        if (validationErrors.length > 0) {
            return res.json({ reply: `Oops! Found some issues:\n- ${validationErrors.join("\n- ")}` });
        }

        // 🚀 Add Job to Build Queue
        // Create project first
        const createdProject = await prisma.project.create({
            data: {
                name: session.name,
                gitUrl: session.gitUrl,
                description: session.description,
                ownerId: parseInt(session.ownerId),
            },
        });

        // Create deployment entry
        const createdDeployment = await prisma.deployment.create({
            data: {
                projectId: createdProject.id,
                status: "PENDING",
            },
        });

        // Then add to queue
        await buildQueue.add('deploy', {
            deploymentId: createdDeployment.id,
            gitUrl: session.gitUrl,
            projectId: createdProject.id
        });
        await buildQueue.add({
            name: String(session.name),
            gitUrl: String(session.gitUrl),
            description: String(session.description),
            ownerId: String(session.ownerId)
        });

        // 🏗️ Clear session after job is added
        delete userSessions[userId];

        return res.json({ reply: `✅ Your project "${session.name}" has been successfully added to the build queue! 🎉` });

    } catch (error) {
        console.error("❌ Error:", error);
        res.status(500).json({ message: "Internal server error." });
    }
};
 
i am getting issue as Worker is Processing deployment for f2257e49-95d3-479a-92c1-c922e7545cbc - Deployment ID: a8fdcb31-9142-4f65-bc91-d339d03ebd83
❌ Error: ReplyError: ERR Lua redis lib command arguments must be strings or integers script
: a7b39766da8f5ced70f465297396dd83e550ceed, on @user_script:298.
    at parseError (D:\Node  js\version control build service\api-server-spinner\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (D:\Node  js\version control build service\api-server-spinner\node_modules\redis-parser\lib\parser.js:302:14) {
  command: {
    name: 'evalsha',
    args: [
      'a7b39766da8f5ced70f465297396dd83e550ceed',
      '8',
      'bull:buildQueue:wait',
      'bull:buildQueue:paused',
      'bull:buildQueue:meta',
      'bull:buildQueue:id',
      'bull:buildQueue:completed',
      'bull:buildQueue:active',
      'bull:buildQueue:events',
      'bull:buildQueue:marker',
      <Buffer 9a b0 62 75 6c 6c 3a 62 75 69 6c 64 51 75 65 75 65 3a a0 de 00 04 a4 6e 61 6d 65 d9 4e 73 68 6f 70 69 66 79 20 20 61 6e 64 20 64 65 73 63 72 69 70 74 ... 254 more bytes>,
      '{}',
      <Buffer de 00 01 a8 61 74 74 65 6d 70 74 73 00>
    ]
  }
}
