### ISSUE TITLE
Redis ECONNRESET causes waitUntilReady to fail

### ISSUE THREAD

**Issue by tayclark** [taskforcesh/bullmq#722]
When the redis connection resets instead of waiting on the connection to re-establish, bull is throwing an error from waitUntilReady. This means that if there are any blips in the redis connection when establishing the worker then there is nothing one can do to wait on the connection to re-establish

**Comment by roggervalf** [comment]
@tayclark could you please try last version, a fix was merged, for now I'll close this issue

**Comment by manast** [comment]
Reference to the fix: https://github.com/taskforcesh/bullmq/pull/751

**Comment by tayclark** [comment]
@roggervalf @manast I don't think this resolved the issue. I tried with the latest version and still seeing failures for `ECONNRESET`. Perhaps the changes should also account for `ECONNRESET` in addition to `ECONNREFUSED`?

**Comment by manast** [comment]
@tayclark could you please post a test case that reproduces the issue so that we can take a look at it?
